// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfRGyKnfnl1LqQ6IwfjmLfvHjy6fp1HwY',
    appId: '1:867178180799:web:0279cc2ef5f50316b5560a',
    messagingSenderId: '867178180799',
    projectId: 'cloth-store-363b3',
    authDomain: 'cloth-store-363b3.firebaseapp.com',
    storageBucket: 'cloth-store-363b3.firebasestorage.app',
    measurementId: 'G-RY1GKKZLYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBawV-2_ErqdCk3BOCPLY6FnZnrshP454I',
    appId: '1:867178180799:android:0bd0a2f5f010b978b5560a',
    messagingSenderId: '867178180799',
    projectId: 'cloth-store-363b3',
    storageBucket: 'cloth-store-363b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfer6Bt1BMwmOgCyEeC2K-1etDNdiSp40',
    appId: '1:867178180799:ios:6076a7f6b975c711b5560a',
    messagingSenderId: '867178180799',
    projectId: 'cloth-store-363b3',
    storageBucket: 'cloth-store-363b3.firebasestorage.app',
    iosBundleId: 'com.example.clotstoreapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfer6Bt1BMwmOgCyEeC2K-1etDNdiSp40',
    appId: '1:867178180799:ios:6076a7f6b975c711b5560a',
    messagingSenderId: '867178180799',
    projectId: 'cloth-store-363b3',
    storageBucket: 'cloth-store-363b3.firebasestorage.app',
    iosBundleId: 'com.example.clotstoreapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfRGyKnfnl1LqQ6IwfjmLfvHjy6fp1HwY',
    appId: '1:867178180799:web:0279cc2ef5f50316b5560a',
    messagingSenderId: '867178180799',
    projectId: 'cloth-store-363b3',
    authDomain: 'cloth-store-363b3.firebaseapp.com',
    storageBucket: 'cloth-store-363b3.firebasestorage.app',
    measurementId: 'G-RY1GKKZLYJ',
  );

}